### ISSUE TITLE
Mask not cleared upon removal of yaml entries

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/autotag-metadata#7]
If you create a YAML entry, such as
![image](https://user-images.githubusercontent.com/39313137/213568108-69eb1778-0b93-4c21-bbf5-e01adf1c6f79.png)

A field in the mask is generated
![image](https://user-images.githubusercontent.com/39313137/213568154-b7ac98a6-9e57-485a-86ce-503ba025beed.png)

However, if you remove the entry in the YAML, the fields in the mask will remain. 
If you try to edit the field, the program will crash.

**Comment by linuxrider** [comment]
I think this is obsolete with the new mask.
